backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "Index Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Intro, name: intro, widget: object, fields: [
                {label: Title, name: title, widget: string}, {label: subtitle, name: subtitle, widget: text}, {label: Image, name: image, widget: image}, {label: ProfileImage, name: profileimage, widget: image}
              ]
            }
      - file: "src/pages/curriculum/index.md"
        label: "Curriculum Page"
        name: "curriculum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "curriculum-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/accomplishments/index.md"
        label: "Accomplishments Page"
        name: "accomplishments"
        create: true
        slug: "{{slug}}"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "accomplishment-item"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Tags", name: "tags", widget: "list"}
